### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by hmontero1205** [belindaleebriggs/prj-rev-bwfs-dasmoto#4]
This project met the requirements outlined by the specs -- good job!

Just a few pointers:

Your code was well written and easy to follow along with. You may want to consider writing HTML comments in the future as your pages get more and more complex.

Be sure to stay consistent with the way you get resources! You downloaded all the images except the banner, which you used a url and the css `background-image` property for. Why?

**Comment by belindaleebriggs** [comment]
Hi!  Thank you so much for reviewing my project - I really appreciate it!

I *could not* get the banner to pull in locally.  I tried a zillion things but none of them worked, except using the online URL. :-(

Some of the things I tried included both using quotes around the path name and omitting them.

I used the Copy Project command in Atom to grab the path for the file. I switched the slashes in the copied project path to forward slashes and prefaced the folder with a ./, but I still could not get it to work.

Which is odd because all of my images, which were located in the same folder, worked fine.

Do you have any recommendations for working with the background-image css property?

I would love to hear your thoughts!

Thank you!
Belinda

**Comment by hmontero1205** [comment]
I've never used Atom so I can't really help you there haha.
I also try to avoid the `background-image` property so I really don't know much about it. This might just be my own personal preference, but I really like using `<img>` to hold backgrounds -- gives me a sense of greater control.
